services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env 
    networks:
      - appnet
  
  server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    restart: always
    ports:
      - 8000:8000
    networks:
      - appnet

  pgvector_db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_PGVECTOR_DB}
      POSTGRES_USER: ${POSTGRES_PGVECTOR_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PGVECTOR_PASSWORD}
    ports:
      - "5433:5433"
    restart: always
    volumes:
      - pgdb:/var/lib/postgresql/data
   
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   volumes:
  #     - redis:/data
  #   env_file:
  #     - .env
  #   networks:
  #     - appnet

  app:
    container_name: agent_bb7
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - agent-data:/agent_bb7/agent_bb7

    restart: unless-stopped
    depends_on:
      # - db
      # - pgvector_db
      # - redis
    networks:
      - appnet
   
networks:
  appnet:
    driver: bridge  
    name: appnet
  
volumes:
  agent-data:
  db:
  chroma-data:
      driver: local
  pgdb:
  # redis: